version: "3"

services:
  ds-cloud:
    command: npm run start:prod
    env_file: /home/cwash/apps/cloud/config/.env.production
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "10m"
    deploy:
      replicas: 9
      resources:
        limits:
          cpus: "1"
      update_config:
        parallelism: 2
        delay: 15s
  nginx:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf.prod:/etc/nginx/conf.d/default.conf
      - /home/cwash/apps/cloud/logs/nginx:/var/log/nginx
      - /home/cwash/apps/cloud/certs/ds-cloud.ru.crt:/etc/ssl/ds-cloud.ru.crt
      - /home/cwash/apps/cloud/certs/ds-cloud.ru.key:/etc/ssl/ds-cloud.ru.key
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"