version: "3"
services:
  ds-cloud:
    env_file: ds-cloud/.env.development
    command: npm run start:dev
    volumes:
      - ./ds-cloud/src:/usr/app/src
  nginx:
    ports:
      - "5051:5051"
    volumes:
      - ./nginx/default.conf.dev:/etc/nginx/conf.d/default.conf